In [29]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import os

In [30]:
%cd ..
%cd data

esg_ind = pd.read_csv('country_esg_indicators.csv')
esg_ind.head()

/Users/jamiewong/Documents/esg-financial-assistant
/Users/jamiewong/Documents/esg-financial-assistant/data

,Country Name,Country Code,Series Name,Series Code,2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Canada,CAN,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,100,100,100,100,..,..
1,Canada,CAN,"Cause of death, by communicable diseases and m...",SH.DTH.COMM.ZS,..,4.77225226729925,..,..,..,..
2,Canada,CAN,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,15.6366541621759,15.0527469447143,13.5993749178773,..,..,..
3,Canada,CAN,Control of Corruption: Estimate,CC.EST,1.78985774517059,1.72997653484344,1.5655562877655,1.61652982234955,1.65857982635498,..
4,Canada,CAN,Economic and Social Rights Performance Score,SD.ESR.PERF.XQ,2.523194195,..,..,..,..,..

In [31]:
esg_ind.tail(10)

,Country Name,Country Code,Series Name,Series Code,2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
639,United States,USA,Strength of legal rights index (0=weak to 12=s...,IC.LGL.CRED.XQ,11,11,..,..,..,..
640,United States,USA,Voice and Accountability: Estimate,VA.EST,0.99573165178299,0.905322194099426,0.855865716934204,0.878146708011627,0.84512186050415,..
641,United States,USA,Terrestrial and marine protected areas (% of t...,ER.PTD.TOTL.ZS,26.328083601169,26.3281159177314,23.9458352965842,15.8832744740312,15.8833371610815,..
642,United States,USA,Tree Cover Loss (hectares),AG.LND.FRLS.HA,2092359,2109918,1966716,2044299,..,..
643,United States,USA,Level of water stress: freshwater withdrawal a...,ER.H2O.FWST.ZS,28.1619842696,28.1619842696,28.1619842696,..,..,..
644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
645,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
647,Data from database: Environment Social and Gov...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
648,Last Updated: 04/16/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
esg_ind = esg_ind.iloc[:-5]

In [33]:
esg_ind.sort_values(by=['Series Name', 'Country Name'], inplace = True)
esg_ind = esg_ind.reset_index(drop = True)
esg_ind.head()

,Country Name,Country Code,Series Name,Series Code,2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Australia,AUS,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,100,100,100,100,..,..
1,Belgium,BEL,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,100,100,100,100,..,..
2,Canada,CAN,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,100,100,100,100,..,..
3,China,CHN,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,77.6,79.4,81.4,83.2,..,..
4,Denmark,DNK,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,100,100,100,100,..,..

In [34]:
print(esg_ind['2023 [YR2023]'].unique())

['..']

In [35]:
esg_ind = esg_ind.drop('2023 [YR2023]', axis = 1)

In [36]:
esg_ind.rename(columns={'2018 [YR2018]': '2018',
                        '2019 [YR2019]': '2019',
                        '2020 [YR2020]': '2020',
                        '2021 [YR2021]': '2021',
                        '2022 [YR2022]': '2022',
                        }, inplace = True)
esg_ind.head()

,Country Name,Country Code,Series Name,Series Code,2018,2019,2020,2021,2022
0,Australia,AUS,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,100,100,100,100,..
1,Belgium,BEL,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,100,100,100,100,..
2,Canada,CAN,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,100,100,100,100,..
3,China,CHN,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,77.6,79.4,81.4,83.2,..
4,Denmark,DNK,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,100,100,100,100,..

In [37]:
esg_ind = esg_ind.replace('..', np.nan)
esg_ind.iloc[56:58]

,Country Name,Country Code,Series Name,Series Code,2018,2019,2020,2021,2022
56,Australia,AUS,"Cause of death, by communicable diseases and m...",SH.DTH.COMM.ZS,NaN,4.94105432186094,NaN,NaN,NaN
57,Belgium,BEL,"Cause of death, by communicable diseases and m...",SH.DTH.COMM.ZS,NaN,7.89790553547321,NaN,NaN,NaN

In [38]:
i = 0
num_inds = esg_ind['Series Code'].nunique()
num_ctrys = esg_ind['Country Code'].nunique()
years = []
while i < num_inds:
    upper = i * num_ctrys
    lower = (i + 1) * num_ctrys
    subset = esg_ind.iloc[upper:lower]
    search = True
    yr = 2022
    while search:
        if subset[str(yr)].isna().sum() == 0:
            years.append(str(yr))
            search = False
        else:
            yr -= 1

    i += 1
print(years)

['2021', '2020', '2019', '2022', '2018', '2022', '2020', '2020', '2020', '2020', '2021', '2020', '2019', '2022', '2022', '2022', '2020', '2022', '2018', '2019', '2022', '2021', '2022']

In [39]:
esg_clean = pd.DataFrame()
esg_clean['Country Name'] = esg_ind['Country Name'].unique()
esg_clean['Country Code'] = esg_ind['Country Code'].unique()
esg_clean.head()

  Country Name Country Code
0    Australia          AUS
1      Belgium          BEL
2       Canada          CAN
3        China          CHN
4      Denmark          DNK

In [40]:
i = 0
col_names = esg_ind['Series Name'].unique()
while i < num_inds:
    upper = i * num_ctrys
    lower = (i + 1) * num_ctrys
    subset = esg_ind.iloc[upper:lower]

    name = col_names[i]
    esg_clean[name] = list(subset[years[i]])

    i += 1
esg_clean.head()

,Country Name,Country Code,Access to clean fuels and technologies for cooking (% of population),CO2 emissions (metric tons per capita),"Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)",Control of Corruption: Estimate,Economic and Social Rights Performance Score,Government Effectiveness: Estimate,"Government expenditure on education, total (% of government expenditure)",Level of water stress: freshwater withdrawal as a proportion of available freshwater resources,...,Political Stability and Absence of Violence/Terrorism: Estimate,Proportion of seats held by women in national parliaments (%),Regulatory Quality: Estimate,Renewable energy consumption (% of total final energy consumption),Rule of Law: Estimate,"School enrollment, primary and secondary (gross), gender parity index (GPI)",Strength of legal rights index (0=weak to 12=strong),Terrestrial and marine protected areas (% of total territorial area),Tree Cover Loss (hectares),Voice and Accountability: Estimate
0,Australia,AUS,100,14.7761369066259,4.94105432186094,1.76448953151703,2.439727414,1.52887463569641,14.3882093429565,3.4740651387,...,0.933572053909302,38.4105960264901,1.89489328861237,10.89,1.51008522510529,0.968850016593933,11,32.1204150724308,261044,1.31948041915894
1,Belgium,BEL,100,7.39813065774681,7.89790553547321,1.49504864215851,2.487935212,1.22765874862671,11.1489362716675,51.5847665848,...,0.575668811798096,42.6666666666667,1.25295519828796,12.28,1.34894239902496,1.0733699798584,8,17.838189781615,9143,1.29260873794556
2,Canada,CAN,100,13.5993749178773,4.77225226729925,1.65857982635498,2.523194195,1.56707048416138,9.87754249572754,3.7335736354,...,0.772814035415649,30.4733727810651,1.67709279060364,23.85,1.56622016429901,1.00332999229431,9,11.3811168673874,2524986,1.43496835231781
3,China,CHN,83.2,7.75613790659769,3.54971055780421,0.0159702487289906,2.532732755,0.495032012462616,10.5329275131226,41.5185287974,...,-0.441073626279831,24.9411764705882,-0.418417632579803,14.81,-0.0414439849555492,1.01431000232697,3,14.7465114295171,536655,-1.60957491397858
4,Denmark,DNK,100,4.69123730751634,6.82614009736737,2.40274429321289,2.493505479,1.9906097650528,11.9155778884888,26.4042725798,...,0.86500883102417,43.5754189944134,1.84312748908997,39.7,1.90030813217163,0.999819993972778,8,17.9019843467964,4795,1.58586609363556

In [41]:
for name in col_names:
    esg_clean[name] = esg_clean[name].apply(pd.to_numeric)
print(esg_clean.dtypes)

Country Name                                                                                              object
Country Code                                                                                              object
Access to clean fuels and technologies for cooking (% of population)                                     float64
CO2 emissions (metric tons per capita)                                                                   float64
Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)    float64
Control of Corruption: Estimate                                                                          float64
Economic and Social Rights Performance Score                                                             float64
Government Effectiveness: Estimate                                                                       float64
Government expenditure on education, total (% of government expenditure)                                 float64
Level of water stress: freshwater withdrawal as a proportion of available freshwater resources           float64
Life expectancy at birth, total (years)                                                                  float64
Methane emissions (metric tons of CO2 equivalent per capita)                                             float64
Mortality rate, under-5 (per 1,000 live births)                                                          float64
Nitrous oxide emissions (metric tons of CO2 equivalent per capita)                                       float64
PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)                                   float64
Political Stability and Absence of Violence/Terrorism: Estimate                                          float64
Proportion of seats held by women in national parliaments (%)                                            float64
Regulatory Quality: Estimate                                                                             float64
Renewable energy consumption (% of total final energy consumption)                                       float64
Rule of Law: Estimate                                                                                    float64
School enrollment, primary and secondary (gross), gender parity index (GPI)                              float64
Strength of legal rights index (0=weak to 12=strong)                                                       int64
Terrestrial and marine protected areas (% of total territorial area)                                     float64
Tree Cover Loss (hectares)                                                                                 int64
Voice and Accountability: Estimate                                                                       float64
dtype: object

In [42]:
school_enrlmt = 'School enrollment, primary and secondary (gross), gender parity index (GPI)'
esg_scaled[school_enrlmt] = abs(1-esg_scaled[school_enrlmt])
esg_scaled.head()

,Access to clean fuels and technologies for cooking (% of population),CO2 emissions (metric tons per capita),"Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)",Control of Corruption: Estimate,Economic and Social Rights Performance Score,Government Effectiveness: Estimate,"Government expenditure on education, total (% of government expenditure)",Level of water stress: freshwater withdrawal as a proportion of available freshwater resources,"Life expectancy at birth, total (years)",Methane emissions (metric tons of CO2 equivalent per capita),...,Political Stability and Absence of Violence/Terrorism: Estimate,Proportion of seats held by women in national parliaments (%),Regulatory Quality: Estimate,Renewable energy consumption (% of total final energy consumption),Rule of Law: Estimate,"School enrollment, primary and secondary (gross), gender parity index (GPI)",Strength of legal rights index (0=weak to 12=strong),Terrestrial and marine protected areas (% of total territorial area),Tree Cover Loss (hectares),Voice and Accountability: Estimate
0,1.000000,-1.000000,-0.043303,0.777642,0.801053,0.737206,0.496589,-0.017164,0.929563,-0.802957,...,0.789436,0.703514,0.878652,0.165148,0.834541,9.300587e-01,0.9,0.791487,-0.103313,0.865447
1,1.000000,-0.441062,-0.135329,0.683773,0.872555,0.608693,0.269879,-0.595589,0.799830,-0.079426,...,0.646263,0.808586,0.634828,0.188173,0.766214,1.776357e-15,0.6,0.410320,-0.003542,0.857507
2,1.000000,-0.910852,-0.038049,0.740744,0.924851,0.753502,0.180897,-0.020284,0.850346,-0.396523,...,0.725127,0.507564,0.795926,0.379824,0.858343,6.232426e-01,0.7,0.237992,-1.000000,0.899570
3,0.418685,-0.468184,-0.000000,0.168484,0.938999,0.296120,0.226766,-0.474564,0.664232,-0.103831,...,0.239535,0.370988,0.000000,0.230081,0.176674,5.255383e-01,0.1,0.327808,-0.212475,0.000000
4,1.000000,-0.235995,-0.101972,1.000000,0.880817,0.934204,0.323535,-0.292849,0.846822,-0.184299,...,0.762008,0.831020,0.858990,0.642372,1.000000,6.544759e-01,0.6,0.412022,-0.001820,0.944156

In [43]:
scaler = preprocessing.MinMaxScaler()
esg_scaled = scaler.fit_transform(esg_clean.iloc[:,2:])
esg_scaled = pd.DataFrame(esg_scaled, columns = col_names)
esg_scaled.head()

,Access to clean fuels and technologies for cooking (% of population),CO2 emissions (metric tons per capita),"Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)",Control of Corruption: Estimate,Economic and Social Rights Performance Score,Government Effectiveness: Estimate,"Government expenditure on education, total (% of government expenditure)",Level of water stress: freshwater withdrawal as a proportion of available freshwater resources,"Life expectancy at birth, total (years)",Methane emissions (metric tons of CO2 equivalent per capita),...,Political Stability and Absence of Violence/Terrorism: Estimate,Proportion of seats held by women in national parliaments (%),Regulatory Quality: Estimate,Renewable energy consumption (% of total final energy consumption),Rule of Law: Estimate,"School enrollment, primary and secondary (gross), gender parity index (GPI)",Strength of legal rights index (0=weak to 12=strong),Terrestrial and marine protected areas (% of total territorial area),Tree Cover Loss (hectares),Voice and Accountability: Estimate
0,1.000000,1.000000,0.043303,0.777642,0.801053,0.737206,0.496589,0.017164,0.929563,0.802957,...,0.789436,0.703514,0.878652,0.165148,0.834541,0.069941,0.9,0.791487,0.103313,0.865447
1,1.000000,0.441062,0.135329,0.683773,0.872555,0.608693,0.269879,0.595589,0.799830,0.079426,...,0.646263,0.808586,0.634828,0.188173,0.766214,1.000000,0.6,0.410320,0.003542,0.857507
2,1.000000,0.910852,0.038049,0.740744,0.924851,0.753502,0.180897,0.020284,0.850346,0.396523,...,0.725127,0.507564,0.795926,0.379824,0.858343,0.376757,0.7,0.237992,1.000000,0.899570
3,0.418685,0.468184,0.000000,0.168484,0.938999,0.296120,0.226766,0.474564,0.664232,0.103831,...,0.239535,0.370988,0.000000,0.230081,0.176674,0.474462,0.1,0.327808,0.212475,0.000000
4,1.000000,0.235995,0.101972,1.000000,0.880817,0.934204,0.323535,0.292849,0.846822,0.184299,...,0.762008,0.831020,0.858990,0.642372,1.000000,0.345524,0.6,0.412022,0.001820,0.944156

In [44]:
neg_fts = ['CO2 emissions (metric tons per capita)',
           'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)',
           'Level of water stress: freshwater withdrawal as a proportion of available freshwater resources',
           'Methane emissions (metric tons of CO2 equivalent per capita)',
           'Mortality rate, under-5 (per 1,000 live births)',
           'Nitrous oxide emissions (metric tons of CO2 equivalent per capita)',
           'PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)',
           'School enrollment, primary and secondary (gross), gender parity index (GPI)',
           'Tree Cover Loss (hectares)'
           ]

for ft in neg_fts:
    esg_scaled[ft] = -1*esg_scaled[ft]



esg_scaled.head()

,Access to clean fuels and technologies for cooking (% of population),CO2 emissions (metric tons per capita),"Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)",Control of Corruption: Estimate,Economic and Social Rights Performance Score,Government Effectiveness: Estimate,"Government expenditure on education, total (% of government expenditure)",Level of water stress: freshwater withdrawal as a proportion of available freshwater resources,"Life expectancy at birth, total (years)",Methane emissions (metric tons of CO2 equivalent per capita),...,Political Stability and Absence of Violence/Terrorism: Estimate,Proportion of seats held by women in national parliaments (%),Regulatory Quality: Estimate,Renewable energy consumption (% of total final energy consumption),Rule of Law: Estimate,"School enrollment, primary and secondary (gross), gender parity index (GPI)",Strength of legal rights index (0=weak to 12=strong),Terrestrial and marine protected areas (% of total territorial area),Tree Cover Loss (hectares),Voice and Accountability: Estimate
0,1.000000,-1.000000,-0.043303,0.777642,0.801053,0.737206,0.496589,-0.017164,0.929563,-0.802957,...,0.789436,0.703514,0.878652,0.165148,0.834541,-0.069941,0.9,0.791487,-0.103313,0.865447
1,1.000000,-0.441062,-0.135329,0.683773,0.872555,0.608693,0.269879,-0.595589,0.799830,-0.079426,...,0.646263,0.808586,0.634828,0.188173,0.766214,-1.000000,0.6,0.410320,-0.003542,0.857507
2,1.000000,-0.910852,-0.038049,0.740744,0.924851,0.753502,0.180897,-0.020284,0.850346,-0.396523,...,0.725127,0.507564,0.795926,0.379824,0.858343,-0.376757,0.7,0.237992,-1.000000,0.899570
3,0.418685,-0.468184,-0.000000,0.168484,0.938999,0.296120,0.226766,-0.474564,0.664232,-0.103831,...,0.239535,0.370988,0.000000,0.230081,0.176674,-0.474462,0.1,0.327808,-0.212475,0.000000
4,1.000000,-0.235995,-0.101972,1.000000,0.880817,0.934204,0.323535,-0.292849,0.846822,-0.184299,...,0.762008,0.831020,0.858990,0.642372,1.000000,-0.345524,0.6,0.412022,-0.001820,0.944156

In [45]:
esg_cats = {'E': ['CO2 emissions (metric tons per capita)',
                  'Level of water stress: freshwater withdrawal as a proportion of available freshwater resources',
                  'Methane emissions (metric tons of CO2 equivalent per capita)',
                  'Nitrous oxide emissions (metric tons of CO2 equivalent per capita)',
                  'PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)',
                  'Renewable energy consumption (% of total final energy consumption)',
                  'Terrestrial and marine protected areas (% of total territorial area)',
                  'Tree Cover Loss (hectares)'
                  ],
            'S': ['Access to clean fuels and technologies for cooking (% of population)',
                  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)',
                  'Government expenditure on education, total (% of government expenditure)',
                  'Life expectancy at birth, total (years)',
                  'Mortality rate, under-5 (per 1,000 live births)'
                  ],
            'G': ['Control of Corruption: Estimate',
                  'Economic and Social Rights Performance Score',
                  'Government Effectiveness: Estimate',
                  'Political Stability and Absence of Violence/Terrorism: Estimate',
                  'Proportion of seats held by women in national parliaments (%)',
                  'Regulatory Quality: Estimate',
                  'Rule of Law: Estimate',
                  'School enrollment, primary and secondary (gross), gender parity index (GPI)',
                  'Strength of legal rights index (0=weak to 12=strong)',
                  'Voice and Accountability: Estimate'
                  ]}

In [46]:
esg_scores = []
for i in range(num_ctrys):
    components = []
    for cat in esg_cats:
        sub_score = 0
        for stat in esg_cats[cat]:
            sub_score += (esg_scaled[stat])[i]
        components.append(sub_score)
    avg = sum(components)/len(components)
    esg_scores.append(avg)

In [47]:
esg_clean['ESG Score'] = esg_scores
esg_clean = esg_clean.sort_values(by = 'ESG Score', ascending=False)
esg_final = esg_clean[['Country Name', 'ESG Score']]
esg_final

      Country Name  ESG Score
17          Norway   3.267407
23          Sweden   3.256376
4          Denmark   3.161803
16     New Zealand   2.838591
6          Germany   2.788788
26  United Kingdom   2.760768
15     Netherlands   2.657659
0        Australia   2.642929
5           France   2.484457
19        Portugal   2.367693
12           Japan   2.216889
1          Belgium   2.215481
20       Singapore   2.122323
2           Canada   2.102173
22           Spain   2.096732
10         Ireland   2.041253
18          Poland   1.976575
11           Italy   1.815777
27   United States   1.744058
13     Korea, Rep.   1.680725
7           Greece   1.471301
14        Malaysia   1.312900
24        Thailand   0.876344
9        Indonesia   0.598180
25         Turkiye   0.581460
3            China   0.547506
21    South Africa   0.043756
8            India  -0.033577

In [48]:
esg_final.to_csv('/Users/jamiewong/Documents/esg-financial-assistant/data/country_esg_scores.csv')